### ISSUE TITLE
Creating credentials fails with - Argument 'private_key' has incorrect type (expected bytes, got str)

### ISSUE THREAD

**Issue by bdebowski** [sandtable/ssl_grpc_example#4]
The code below fails on my machine with error - Argument 'private_key' has incorrect type (expected bytes, got str):

        with open('server.key') as f:
            private_key = f.read()
        with open('server.crt') as f:
            certificate_chain = f.read()
        server_credentials = grpc.ssl_server_credentials(
            ((private_key, certificate_chain,),))

I wrapped the strings like so bytes(private_key, 'utf-8') and that seemed to fix it

**Comment by bdebowski** [comment]
confirmed, changing those lines to:

        server_credentials = grpc.ssl_server_credentials(
            ((bytes(private_key, 'utf-8'), bytes(certificate_chain, 'utf-8'),),))

fixed the issue.  Similar change on client side required.  Recommend updating the code in this repo to reflect this.

**Comment by tfrench** [comment]
Thanks for letting us know. I'll update the repo. 

It's easier to read in as bytes: `open('', 'rb')`
